export interface AtticData {
    name: string;
    date: string;
    address: string;
    phoneNumber: string;
    emailAddress: string;
    homeownerConcerns: string;
    rebateOpportunities: string;
    joistSpacing: '16"' | '24"';
    roofStructure: 'Trusses' | 'Stick Built';
    ridgeVent: boolean;
    ventedSoffit: boolean;
    soffitBaffles: boolean;
    condensationEvidence: boolean;
    rodentEvidence: boolean;
    insType: string;
    insThickness: string;
    currentRValue: string;
    airSealing: boolean;
    hvacInAttic: boolean;
    accessHatchType: string;
    accessHatchSize: string;
    atticSection1Dimensions: string;
    atticSection1UnflooredArea: string;
    atticSection1FlooredArea: string;
    atticSection1TotalArea: string;
    atticSection1FlooredAreaCavityDepth: string;
    atticSection2Location: string;
    atticSection2UnflooredArea: string;
    atticSection2FlooredArea: string;
    atticSection2TotalArea: string;
    atticSection2FlooredAreaCavityDepth: string;
    atticSection3Dimensions: string;
    atticSection3UnflooredArea: string;
    atticSection3FlooredArea: string;
    atticSection3TotalArea: string;
    atticSection3FlooredAreaCavityDepth: string;
    additionalNotes: string;
    atticInsRecommendations: string;
    atticASRecommendations: string;
    atticAccessInsAsRecommendations: string;
    thermopanDamsRecommendations: string;
    soffitVentilationRecommendations: string;
    additionalServices: string;
  }